utils::globalVariables(c("rh",
                         "value",
                         "solution",
                         ".",
                         "Date",
                         "Temperature",
                         "Probe",
                         "start",
                         "end"))
